services:
  prodution-frontend:
    build:
      context: .
      args:
        MAIN_PATH: prodution-frontend/main.go
    ports:
      - "8081:8081"
    environment:
      - POSTGRESQL_URI=postgresql://postgres:example@postgres:5432/postgres
    depends_on:
      - postgres

  voters-frontend:
    build:
      context: .
      args:
        MAIN_PATH: voters-frontend/main.go
    ports:
      - "8080:8080"
    environment:
      - POSTGRESQL_URI=postgresql://postgres:example@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
      - KAFKA_URI=kafka:9092
    depends_on:
      - postgres
      - kafka

  voters-register:
    build:
      context: .
      args:
        MAIN_PATH: votes-register/main.go
    environment:
      - POSTGRESQL_URI=postgresql://postgres:example@postgres:5432/postgres
      - KAFKA_URI=kafka:9092
    depends_on:
      - postgres
      - kafka

  postgres:
    image: postgres:15.3
    attach: false
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./local_data/postgres:/var/lib/postgresql/data
      - ./ddl:/ddl

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    attach: false
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    attach: false
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
