services:
  prodution-frontend:
    build:
      context: .
      args:
        MAIN_PATH: prodution-frontend/main.go
    ports:
      - "8081:8081"
    environment:
      - POSTGRESQL_URI=postgresql://postgres:example@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  voters-frontend:
    build:
      context: .
      args:
        MAIN_PATH: voters-frontend/main.go
    ports:
      - "8080:8080"
    environment:
      - POSTGRESQL_URI=postgresql://postgres:example@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
      - KAFKA_URI=kafka-1:29092,kafka-2:29093
    depends_on:
      - postgres
      - kafka-1
      - kafka-2
      - redis

  voters-register:
    build:
      context: .
      args:
        MAIN_PATH: votes-register/main.go
    environment:
      - POSTGRESQL_URI=postgresql://postgres:example@postgres:5432/postgres
      - KAFKA_URI=kafka-1:29092,kafka-2:29093
    depends_on:
      - postgres
      - kafka-1
      - kafka-2

  postgres:
    image: postgres:15.3
    attach: false
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./local_data/postgres:/var/lib/postgresql/data
      - ./ddl:/ddl

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    attach: false
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    attach: false
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTER_DOCKER://0.0.0.0:29092,INTER_BROKER://0.0.0.0:39092,DOCKER_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTER_DOCKER://kafka-1:29092,INTER_BROKER://kafka-1:39092,DOCKER_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTER_DOCKER:PLAINTEXT,INTER_BROKER:PLAINTEXT,DOCKER_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: INTER_BROKER
    depends_on:
      - zookeeper

  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    attach: false
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTER_DOCKER://0.0.0.0:29093,INTER_BROKER://0.0.0.0:39093,DOCKER_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTER_DOCKER://kafka-2:29093,INTER_BROKER://kafka-2:39093,DOCKER_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTER_DOCKER:PLAINTEXT,INTER_BROKER:PLAINTEXT,DOCKER_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: INTER_BROKER
    depends_on:
      - zookeeper

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  k6:
    build: k6/.
    environment:
      URL: "http://voters-frontend:8080"
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring-provisioning/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring-provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring-provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitoring-provisioning/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - prometheus
