definitions:
  domain.Participant:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  domain.Vote:
    properties:
      participant:
        $ref: '#/definitions/domain.Participant'
      timestamp:
        type: string
      voteID:
        type: integer
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Responds with an HTML page with the index page
      produces:
      - text/html
      responses:
        "200":
          description: HTML Content
          schema:
            type: string
      summary: Serve HTML index page
      tags:
      - html
  /after-vote:
    get:
      description: Responds with an HTML page with a rought total graph
      produces:
      - text/html
      responses:
        "200":
          description: HTML Content
          schema:
            type: string
      summary: Serve HTML rought total page
      tags:
      - html
  /api/participants:
    get:
      consumes:
      - application/json
      description: Responds with the list of participants
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Participant'
            type: array
      summary: Get Participants
      tags:
      - api
  /api/votes:
    post:
      consumes:
      - application/json
      description: Cast a Vote
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Vote'
      summary: Post Vote
      tags:
      - api
  /api/votes/totals/rough:
    get:
      consumes:
      - application/json
      description: Get rough totals
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Get Rough Totals
      tags:
      - api
swagger: "2.0"
