apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-2
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      broker: "2"
  template:
    metadata:
      labels:
        app: kafka
        broker: "2"
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9093
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker-2:9093
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9093
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-2
  labels:
    app: kafka
    broker: "2"
spec:
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: kafka
    broker: "2"
