apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: load-test
  labels:
    app: load-test
spec:
  template:
    metadata:
      labels:
        app: load-test
    spec:
      containers:
        - name: load-test
          image: load-test:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: URL
              value: "http://voters-frontend:8080"
      restartPolicy: Never
