apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodution-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prodution-frontend
  template:
    metadata:
      labels:
        app: prodution-frontend
    spec:
      containers:
        - name: prodution-frontend
          image: prodution-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRESQL_URI
              value: "postgresql://postgres:example@postgres:5432/postgres"
            - name: REDIS_URL
              value: "redis://redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: prodution-frontend
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: prodution-frontend
