apiVersion: apps/v1
kind: Deployment
metadata:
  name: voters-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voters-frontend
  template:
    metadata:
      labels:
        app: voters-frontend
    spec:
      containers:
        - name: voters-frontend
          image: voters-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRESQL_URI
              value: "postgresql://postgres:example@postgres:5432/postgres"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: KAFKA_URI
              value: "kafka-broker-1:9092,kafka-broker-2:9093"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: voters-frontend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voters-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: voters-frontend
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: voters-frontend
