// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Responds with an HTML page with a thorough total graph",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "html"
                ],
                "summary": "Serve HTML thorough total page",
                "responses": {
                    "200": {
                        "description": "HTML Content",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/votes/totals/thorough": {
            "get": {
                "description": "Get throught totals",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "Get Thorough Totals",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ThoroughTotalsResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.ThoroughTotalsResponseModel": {
            "type": "object",
            "properties": {
                "general_total": {
                    "type": "integer"
                },
                "total_by_hour": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.TotalByHour"
                    }
                },
                "total_by_participant": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        },
        "domain.TotalByHour": {
            "type": "object",
            "properties": {
                "hour": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
