definitions:
  controller.ThoroughTotalsResponseModel:
    properties:
      general_total:
        type: integer
      total_by_hour:
        items:
          $ref: '#/definitions/domain.TotalByHour'
        type: array
      total_by_participant:
        additionalProperties:
          type: integer
        type: object
    type: object
  domain.TotalByHour:
    properties:
      hour:
        type: string
      total:
        type: integer
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Responds with an HTML page with a thorough total graph
      produces:
      - text/html
      responses:
        "200":
          description: HTML Content
          schema:
            type: string
      summary: Serve HTML thorough total page
      tags:
      - html
  /api/votes/totals/thorough:
    get:
      consumes:
      - application/json
      description: Get throught totals
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ThoroughTotalsResponseModel'
      summary: Get Thorough Totals
      tags:
      - api
swagger: "2.0"
