definitions:
  controller.ThoroughTotalsResponseModel:
    properties:
      general_total:
        type: integer
      total_by_hour:
        items:
          $ref: '#/definitions/domain.TotalByHour'
        type: array
      total_by_participant:
        additionalProperties:
          type: integer
        type: object
    type: object
  domain.TotalByHour:
    properties:
      hour:
        type: integer
      total:
        type: integer
    type: object
info:
  contact: {}
paths:
  /votes/thorough:
    get:
      consumes:
      - application/json
      description: Get throught totals
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ThoroughTotalsResponseModel'
      summary: Get Thorough Totals
      tags:
      - Totals Votes
swagger: "2.0"
